version: "3.8"
services:
  apigateway:
    image: apigateway:latest
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - "5001:8080"
    depends_on:
      - identityservice
      - favoriteservice
      - musicservice
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - musicapp-network

  identityservice:
    image: identityservice:latest
    build:
      context: .
      dockerfile: IdentityService/Dockerfile
    ports:
      - "8444:8080"
    volumes:
      - profile-pictures:/app/profile_pictures
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - musicapp-network

  favoriteservice:
    image: favoriteservice:latest
    build:
      context: .
      dockerfile: FavoritesService/Dockerfile
    ports:
      - "8446:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      REDIS_CONNECTION: redis:6379
    depends_on:
      - redis
    networks:
      - musicapp-network

  musicservice:
    image: musicservice:latest
    build:
      context: .
      dockerfile: MusicService/Dockerfile
    ports:
      - "8445:8080"
    volumes:
      - music-files:/app/music_files
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - musicapp-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - musicapp-network

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - musicapp-network

  musicapp:
    build:
      context: ./musicapp
      dockerfile: Dockerfile
    container_name: musicapp
    ports:
      - "5173:5173" 
    volumes:
      - profile-pictures:/app/music_files
      - ./musicapp:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    networks:
      - musicapp-network

volumes:
  profile-pictures:
    driver: local
  music-files:
    driver: local

networks:
  musicapp-network:
    driver: bridge
